from __future__ import annotations

import json
import re
from pathlib import Path

import pdfplumber


REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
SOURCE_PDF = (
    REPOSITORY_ROOT
    / "assets"
    / "rules"
    / "index-of-the-untold-campaign-mode.pdf"
)
OUTPUT_MODULE = REPOSITORY_ROOT / "worker" / "src" / "rules-data.js"

PAGE_TITLES = {
    14: "Introduction",
    15: "Starting the Campaign",
    17: "Building a Leader",
    18: "Start of a New Week",
    19: "Setting Up a Game",
    20: "Playing and Aftermath",
    21: "Payday and Barter",
    22: "Equipment Tables",
    29: "Those Who Thirst",
    31: "Advance Leader",
    33: "Back-Alley Doctor",
    34: "Determine Injuries",
    36: "Lucky Miss",
    37: "Ending a Campaign",
    38: "Tier 1 Attack",
    41: "Tier 1 Tactical",
    44: "Tier 2 Actions",
    50: "Tier 2 Abilities",
    52: "Tier 3 Totem",
    54: "Tier 3 Summoning",
    55: "Illustration",
    56: "Arsenal Sheet",
}


def clean_page_text(value: str) -> str:
    lines = []
    for raw_line in value.replace("\u00a0", " ").replace("\u00ad", "").splitlines():
        line = re.sub(r"[ \t]+", " ", raw_line).strip()
        if line:
            lines.append(line)
    return "\n".join(lines)


def main() -> None:
    pages = []
    with pdfplumber.open(SOURCE_PDF) as document:
        if len(document.pages) != 43:
            raise RuntimeError(f"Expected 43 campaign pages, found {len(document.pages)}")

        for index, pdf_page in enumerate(document.pages):
            printed_page = index + 14
            pages.append(
                {
                    "page": printed_page,
                    "title": PAGE_TITLES.get(printed_page, ""),
                    "text": clean_page_text(pdf_page.extract_text() or ""),
                }
            )

    payload = json.dumps(pages, ensure_ascii=False, indent=2)
    OUTPUT_MODULE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_MODULE.write_text(
        "/* Generated by worker/scripts/extract-rules.py. */\n"
        f"export const RULE_PAGES = {payload};\n",
        encoding="utf-8",
        newline="\n",
    )

    text_pages = sum(bool(page["text"]) for page in pages)
    print(
        f"Wrote {len(pages)} pages ({text_pages} with extracted text) "
        f"to {OUTPUT_MODULE}"
    )


if __name__ == "__main__":
    main()
