(() => {
  "use strict";

  function deepFreeze(value) {
    if (!value || typeof value !== "object" || Object.isFrozen(value)) return value;
    Object.values(value).forEach(deepFreeze);
    return Object.freeze(value);
  }

  function namedResult(id, value, name, page) {
    return { id, value, name, page };
  }

  function actionSnapshot({
    id,
    name,
    type,
    range = null,
    rangeType = null,
    skill = null,
    skillSuits = [],
    positiveSkill = false,
    resist = null,
    tn = null,
    damage = null,
    signature = false,
    stoneCost = 0,
    text = "",
    triggers = [],
  }) {
    return {
      id,
      name,
      type,
      range,
      rangeType,
      skill,
      skillSuits,
      positiveSkill,
      resist,
      tn,
      damage,
      signature,
      stoneCost,
      text,
      triggers,
    };
  }

  const XP_TRACK = [
    1, 1, 2, null, 3, null, 4, null, 1, null, 2, null, 4,
    null, null, null, 1, null, null, 2, 1, null, null, null, 3, null,
    null, null, null, 1, null, null, null, null, 2, null, null, null, 4,
  ];

  const XP_THRESHOLDS = XP_TRACK.flatMap((maxTier, index) =>
    maxTier === null ? [] : [{ xp: index + 1, maxTier }],
  );

  const TABLES = {
    "attack-modification": {
      id: "attack-modification",
      tier: 1,
      name: "Attack Modification Advancement",
      pages: [38, 39, 40],
      selection: "at-or-below",
      target: "attack",
      recipients: ["leader", "totem"],
      repeatability: "unique-per-result-and-action",
      resultTypes: ["trigger", "skill", "signature"],
      triggerSurcharge: { existingTriggerCount: 2, scrip: 2 },
      duplicateTriggersAllowed: false,
    },
    "tactical-modification": {
      id: "tactical-modification",
      tier: 1,
      name: "Tactical Modification Advancement",
      pages: [41, 42, 43],
      selection: "at-or-below",
      target: "tactical",
      recipients: ["leader", "totem"],
      repeatability: "unique-per-result-and-action",
      resultTypes: ["trigger", "skill", "signature"],
      triggerSurcharge: { existingTriggerCount: 2, scrip: 2 },
      duplicateTriggersAllowed: false,
    },
    action: {
      id: "action",
      tier: 2,
      name: "Action Advancement",
      pages: [44, 45, 46, 47, 48, 49],
      selection: "at-or-below",
      recipients: ["leader", "totem"],
      repeatability: "unique-per-recipient",
      resultTypes: ["action", "natural-joker-choice"],
      naturalJokerChoice: true,
      cheatedJokerUsesCardValue: true,
    },
    ability: {
      id: "ability",
      tier: 2,
      name: "Ability Advancement",
      pages: [50, 51],
      selection: "at-or-below",
      recipients: ["leader", "totem"],
      repeatability: "unique-per-recipient",
      resultTypes: ["ability", "natural-joker-choice"],
      naturalJokerChoice: true,
      cheatedJokerUsesCardValue: true,
    },
    totem: {
      id: "totem",
      tier: 3,
      name: "Totem Advancement",
      pages: [52, 53],
      selection: "exact",
      recipients: ["leader"],
      repeatability: "once-while-active",
      resultTypes: ["totem"],
      requiresNoActiveTotem: true,
    },
    summoning: {
      id: "summoning",
      tier: 3,
      name: "Summoning Advancement",
      pages: [54],
      selection: "free-choice",
      recipients: ["leader", "totem"],
      repeatability: "once-per-campaign",
      resultTypes: ["action"],
      oncePerCampaign: true,
    },
    "crew-card": {
      id: "crew-card",
      tier: 4,
      name: "Crew Card Advancement",
      pages: [32, 33],
      selection: "free-choice",
      recipients: ["leader"],
      repeatability: "unique-per-name",
      resultTypes: ["crew-card-effect"],
    },
  };

  const ATTACK_MODIFICATION_OPTIONS = [
    { id: "attack-1-dismember", value: 1, suit: "crow", type: "trigger", name: "Dismember", page: 38 },
    { id: "attack-1-ripped-to-shreds", value: 1, suit: "mask", type: "trigger", name: "Ripped to Shreds", page: 38 },
    { id: "attack-1-drink-blood", value: 1, suit: "ram", type: "trigger", name: "Drink Blood", page: 38 },
    { id: "attack-1-analyze-weakness", value: 1, suit: "tome", type: "trigger", name: "Analyze Weakness", page: 38 },
    { id: "attack-1-heavy-fall", value: 1, suit: "soulstone", type: "trigger", name: "Heavy Fall", page: 38 },
    { id: "attack-2-finality", value: 2, suit: "crow", type: "trigger", name: "Finality", page: 38 },
    { id: "attack-2-advance", value: 2, suit: "mask", type: "trigger", name: "Advance", page: 38 },
    { id: "attack-2-and-stay-there", value: 2, suit: "ram", type: "trigger", name: "And Stay There!", page: 38 },
    { id: "attack-2-marked", value: 2, suit: "tome", type: "trigger", name: "Marked", page: 38 },
    { id: "attack-3-convulsions", value: 3, suit: "crow", type: "trigger", name: "Convulsions", page: 38 },
    { id: "attack-3-bowled-over", value: 3, suit: "mask", type: "trigger", name: "Bowled Over", page: 38 },
    { id: "attack-3-collision", value: 3, suit: "ram", type: "trigger", name: "Collision", page: 38 },
    { id: "attack-3-arcane-jolt", value: 3, suit: "tome", type: "trigger", name: "Arcane Jolt", page: 38 },
    { id: "attack-4-delay", value: 4, suit: "crow", type: "trigger", name: "Delay", page: 38 },
    { id: "attack-4-confusing-feelings", value: 4, suit: "mask", type: "trigger", name: "Confusing Feelings", page: 38 },
    { id: "attack-4-defensive-reflexes", value: 4, suit: "ram", type: "trigger", name: "Defensive Reflexes", page: 38 },
    { id: "attack-4-auto-repair", value: 4, suit: "tome", type: "trigger", name: "Auto-Repair", page: 38 },
    { id: "attack-5-infect", value: 5, suit: "crow", type: "trigger", name: "Infect", page: 38 },
    { id: "attack-5-reposition", value: 5, suit: "mask", type: "trigger", name: "Reposition", page: 38 },
    { id: "attack-5-dumbfounded", value: 5, suit: "ram", type: "trigger", name: "Dumbfounded", page: 38 },
    { id: "attack-5-beautiful-clothes", value: 5, suit: "tome", type: "trigger", name: "Beautiful Clothes", page: 38 },
    { id: "attack-6-drain-magic", value: 6, suit: "crow", type: "trigger", name: "Drain Magic", page: 39 },
    { id: "attack-6-follow-my-path", value: 6, suit: "mask", type: "trigger", name: "Follow My Path", page: 39 },
    { id: "attack-6-eyes-peeled", value: 6, suit: "ram", type: "trigger", name: "Eyes Peeled", page: 39 },
    { id: "attack-6-buffeted-by-wind", value: 6, suit: "tome", type: "trigger", name: "Buffeted by Wind", page: 39 },
    { id: "attack-7-draw-their-attention", value: 7, suit: "crow", type: "trigger", name: "Draw Their Attention", page: 39 },
    { id: "attack-7-four-leafed-clover", value: 7, suit: "mask", type: "trigger", name: "Four-Leafed Clover", page: 39 },
    { id: "attack-7-finisher", value: 7, suit: "ram", type: "trigger", name: "Finisher", page: 39 },
    { id: "attack-7-field-kit", value: 7, suit: "tome", type: "trigger", name: "Field Kit", page: 39 },
    {
      id: "attack-7-skill-boost",
      value: 7,
      suit: null,
      type: "skill",
      name: "Skill Boost",
      page: 39,
      requirements: { currentSkill: [4], resist: ["Df", "Wp"] },
      result: { skill: 5 },
    },
    { id: "attack-8-blank-stare", value: 8, suit: "crow", type: "trigger", name: "Blank Stare", page: 39 },
    { id: "attack-8-aggressive-interrogation", value: 8, suit: "mask", type: "trigger", name: "Aggressive Interrogation", page: 39 },
    { id: "attack-8-flaming-aura", value: 8, suit: "ram", type: "trigger", name: "Flaming Aura", page: 39 },
    { id: "attack-8-drink-up", value: 8, suit: "tome", type: "trigger", name: "Drink Up", page: 39 },
    { id: "attack-9-forgetful", value: 9, suit: "crow", type: "trigger", name: "Forgetful", page: 39 },
    { id: "attack-9-mass-hysteria", value: 9, suit: "mask", type: "trigger", name: "Mass Hysteria", page: 39 },
    { id: "attack-9-always-eating", value: 9, suit: "ram", type: "trigger", name: "Always Eating", page: 39 },
    { id: "attack-9-draw-out-secrets", value: 9, suit: "tome", type: "trigger", name: "Draw Out Secrets", page: 39 },
    { id: "attack-10-ahhh-my-eye", value: 10, suit: "crow", type: "trigger", name: "“AHHH, MY EYE!”", page: 39 },
    { id: "attack-10-precise-strike", value: 10, suit: "mask", type: "trigger", name: "Precise Strike", page: 39 },
    {
      id: "attack-10-heave",
      value: 10,
      suit: "ram",
      type: "trigger",
      name: "Heave",
      description: "Place the target anywhere within 3\" of this model.",
      page: 39,
    },
    { id: "attack-10-wildly-flailing", value: 10, suit: "tome", type: "trigger", name: "Wildly Flailing", page: 40 },
    {
      id: "attack-10-skill-boost",
      value: 10,
      suit: null,
      type: "skill",
      name: "Skill Boost",
      page: 40,
      requirements: { currentSkill: [5], resist: ["Df", "Wp"] },
      result: { skill: 6 },
    },
    { id: "attack-11-loss-for-words", value: 11, suit: "crow", type: "trigger", name: "Loss for Words", page: 40 },
    {
      id: "attack-11-on-your-heels",
      value: 11,
      suit: "mask",
      type: "trigger",
      name: "On Your Heels",
      description: "Place this model into base contact with the target.",
      page: 40,
    },
    { id: "attack-11-critical-strike", value: 11, suit: "ram", type: "trigger", name: "Critical Strike", page: 40 },
    { id: "attack-11-snails-pace", value: 11, suit: "tome", type: "trigger", name: "Snail’s Pace", page: 40 },
    { id: "attack-12-maim", value: 12, suit: "crow", type: "trigger", name: "Maim", page: 40 },
    { id: "attack-12-accidental-roll-over", value: 12, suit: "mask", type: "trigger", name: "Accidental Roll Over", page: 40 },
    { id: "attack-12-pull-and-drag", value: 12, suit: "ram", type: "trigger", name: "Pull and Drag", page: 40 },
    { id: "attack-12-sweeping-strike", value: 12, suit: "tome", type: "trigger", name: "Sweeping Strike", page: 40 },
    {
      id: "attack-12-skill-boost",
      value: 12,
      suit: null,
      type: "skill",
      name: "Skill Boost",
      page: 40,
      requirements: { currentSkill: [6], resist: ["Df", "Wp"] },
      result: { skill: 7 },
    },
    { id: "attack-13-tactical-advantage", value: 13, suit: "crow", type: "trigger", name: "Tactical Advantage", page: 40 },
    { id: "attack-13-cruelty", value: 13, suit: "mask", type: "trigger", name: "Cruelty", page: 40 },
    { id: "attack-13-pump-action", value: 13, suit: "ram", type: "trigger", name: "Pump Action", page: 40 },
    { id: "attack-13-arc", value: 13, suit: "tome", type: "trigger", name: "Arc", page: 40 },
    { id: "attack-13-wild-toss", value: 13, suit: "soulstone", type: "trigger", name: "Wild Toss", page: 40 },
    { id: "attack-13-signature", value: 13, suit: null, type: "signature", name: "Attack Signature", page: 40 },
    { id: "attack-joker-cruel-lessons", value: "any-joker", suit: "soulstone", type: "trigger", name: "Cruel Lessons", page: 40 },
    { id: "attack-joker-consult-the-bones", value: "any-joker", suit: "soulstone", type: "trigger", name: "Consult the Bones", page: 40 },
  ];

  const TACTICAL_MODIFICATION_OPTIONS = [
    { id: "tactical-1-eau-de-bayou", value: 1, suit: "crow", type: "trigger", name: "Eau de Bayou", page: 41 },
    { id: "tactical-1-hey-it-worked", value: 1, suit: "mask", type: "trigger", name: "“Hey, It Worked!”", page: 41 },
    { id: "tactical-1-fix-it", value: 1, suit: "ram", type: "trigger", name: "Fix it!", page: 41 },
    { id: "tactical-1-fuuuuture", value: 1, suit: "tome", type: "trigger", name: "“Fuuuuture!”", page: 41 },
    { id: "tactical-1-revelation", value: 1, suit: "crow", type: "trigger", name: "Revelation", page: 41 },
    { id: "tactical-1-hidden-rope", value: 1, suit: "mask", type: "trigger", name: "Hidden Rope", page: 41 },
    { id: "tactical-1-iron-resolve", value: 1, suit: "ram", type: "trigger", name: "Iron Resolve", page: 41 },
    { id: "tactical-1-price-of-knowledge", value: 1, suit: "tome", type: "trigger", name: "Price of Knowledge", page: 41 },
    { id: "tactical-1-resourceful", value: 1, suit: "soulstone", type: "trigger", name: "Resourceful", page: 41 },
    { id: "tactical-2-hasten", value: 2, suit: "crow", type: "trigger", name: "Hasten", page: 41 },
    { id: "tactical-2-ive-got-your-back", value: 2, suit: "mask", type: "trigger", name: "“I’ve Got Your Back!”", page: 41 },
    { id: "tactical-2-lethal-aura", value: 2, suit: "ram", type: "trigger", name: "Lethal Aura", page: 41 },
    { id: "tactical-2-inner-peace", value: 2, suit: "tome", type: "trigger", name: "Inner Peace", page: 41 },
    { id: "tactical-3-i-can-dig-it", value: 3, suit: "crow", type: "trigger", name: "I Can Dig It", page: 41 },
    { id: "tactical-3-advance", value: 3, suit: "mask", type: "trigger", name: "Advance", page: 41 },
    { id: "tactical-3-mend", value: 3, suit: "ram", type: "trigger", name: "Mend", page: 41 },
    { id: "tactical-3-preparations", value: 3, suit: "tome", type: "trigger", name: "Preparations", page: 41 },
    { id: "tactical-4-rot-away", value: 4, suit: "crow", type: "trigger", name: "Rot Away", page: 41 },
    { id: "tactical-4-reposition", value: 4, suit: "mask", type: "trigger", name: "Reposition", page: 41 },
    { id: "tactical-4-pull-and-drag", value: 4, suit: "ram", type: "trigger", name: "Pull and Drag", page: 41 },
    { id: "tactical-4-purification", value: 4, suit: "tome", type: "trigger", name: "Purification", page: 41 },
    { id: "tactical-5-perilous-ground", value: 5, suit: "crow", type: "trigger", name: "Perilous Ground", page: 41 },
    { id: "tactical-5-herd-the-pack", value: 5, suit: "mask", type: "trigger", name: "Herd the Pack", page: 42 },
    { id: "tactical-5-take-a-bow", value: 5, suit: "ram", type: "trigger", name: "Take a Bow", page: 42 },
    { id: "tactical-5-fortify", value: 5, suit: "tome", type: "trigger", name: "Fortify", page: 42 },
    { id: "tactical-6-unnatural-vigor", value: 6, suit: "crow", type: "trigger", name: "Unnatural Vigor", page: 42 },
    { id: "tactical-6-four-leafed-clover", value: 6, suit: "mask", type: "trigger", name: "Four-Leafed Clover", page: 42 },
    { id: "tactical-6-eyes-peeled", value: 6, suit: "ram", type: "trigger", name: "Eyes Peeled", page: 42 },
    { id: "tactical-6-visions-of-glamour", value: 6, suit: "tome", type: "trigger", name: "Visions of Glamour", page: 42 },
    { id: "tactical-7-without-warning", value: 7, suit: "crow", type: "trigger", name: "Without Warning", page: 42 },
    { id: "tactical-7-keep-your-distance", value: 7, suit: "mask", type: "trigger", name: "Keep Your Distance", page: 42 },
    { id: "tactical-7-shrug-off", value: 7, suit: "ram", type: "trigger", name: "Shrug Off", page: 42 },
    { id: "tactical-7-survival-skills", value: 7, suit: "tome", type: "trigger", name: "Survival Skills", page: 42 },
    {
      id: "tactical-7-skill-boost",
      value: 7,
      suit: null,
      type: "skill",
      name: "Skill Boost",
      page: 42,
      requirements: { currentSkill: [0, 1] },
      result: { skill: 2 },
    },
    { id: "tactical-8-wolf-down", value: 8, suit: "crow", type: "trigger", name: "Wolf Down", page: 42 },
    { id: "tactical-8-pulled-here-and-there", value: 8, suit: "mask", type: "trigger", name: "Pulled Here and There", page: 42 },
    { id: "tactical-8-full-steam", value: 8, suit: "ram", type: "trigger", name: "Full Steam", page: 42 },
    { id: "tactical-8-catch-a-glimpse", value: 8, suit: "tome", type: "trigger", name: "Catch a Glimpse", page: 42 },
    { id: "tactical-9-spiked-coffee", value: 9, suit: "crow", type: "trigger", name: "Spiked Coffee", page: 42 },
    { id: "tactical-9-quick-reflexes", value: 9, suit: "mask", type: "trigger", name: "Quick Reflexes", page: 42 },
    { id: "tactical-9-show-of-force", value: 9, suit: "ram", type: "trigger", name: "Show of Force", page: 42 },
    { id: "tactical-9-maneuver", value: 9, suit: "tome", type: "trigger", name: "Maneuver", page: 42 },
    { id: "tactical-10-quicksand", value: 10, suit: "crow", type: "trigger", name: "Quicksand", page: 42 },
    { id: "tactical-10-erase-their-legacy", value: 10, suit: "mask", type: "trigger", name: "Erase Their Legacy", page: 43 },
    { id: "tactical-10-focused-cleansing", value: 10, suit: "ram", type: "trigger", name: "Focused Cleansing", page: 43 },
    { id: "tactical-10-enchant", value: 10, suit: "tome", type: "trigger", name: "Enchant", page: 43 },
    { id: "tactical-11-soulfire", value: 11, suit: "crow", type: "trigger", name: "Soulfire", page: 43 },
    { id: "tactical-11-never-tell-me-the-odds", value: 11, suit: "mask", type: "trigger", name: "Never Tell Me the Odds", page: 43 },
    { id: "tactical-11-secret-beneath-the-rib", value: 11, suit: "ram", type: "trigger", name: "Secret Beneath the Rib", page: 43 },
    { id: "tactical-11-forethought", value: 11, suit: "tome", type: "trigger", name: "Forethought", page: 43 },
    { id: "tactical-12-prioritize", value: 12, suit: "crow", type: "trigger", name: "Prioritize", page: 43 },
    { id: "tactical-12-vanish", value: 12, suit: "mask", type: "trigger", name: "Vanish", page: 43 },
    { id: "tactical-12-retrace-steps", value: 12, suit: "ram", type: "trigger", name: "Retrace Steps", page: 43 },
    { id: "tactical-12-pass-through", value: 12, suit: "tome", type: "trigger", name: "Pass Through", page: 43 },
    {
      id: "tactical-12-skill-boost",
      value: 12,
      suit: null,
      type: "skill",
      name: "Skill Boost",
      page: 43,
      requirements: { currentSkill: [2, 3] },
      result: { skill: 4 },
    },
    { id: "tactical-13-looks-edible", value: 13, suit: "crow", type: "trigger", name: "“Looks Edible?”", page: 43 },
    { id: "tactical-13-coordinated-attack", value: 13, suit: "mask", type: "trigger", name: "Coordinated Attack", page: 43 },
    { id: "tactical-13-overwhelming-aggression", value: 13, suit: "ram", type: "trigger", name: "Overwhelming Aggression", page: 43 },
    { id: "tactical-13-swap-stories", value: 13, suit: "tome", type: "trigger", name: "Swap Stories", page: 43 },
    { id: "tactical-13-blood-for-power", value: 13, suit: "soulstone", type: "trigger", name: "Blood for Power", page: 43 },
    { id: "tactical-13-signature", value: 13, suit: null, type: "signature", name: "Tactical Signature", page: 43 },
    { id: "tactical-red-joker-illumination-of-illios", value: "red-joker", suit: "soulstone", type: "trigger", name: "Illumination of Illios", page: 43 },
    { id: "tactical-black-joker-darkness-of-delios", value: "black-joker", suit: "soulstone", type: "trigger", name: "Darkness of Delios", page: 43 },
  ];

  const TIER_2_ACTIONS = {
    always: [
      namedResult("action-tap-the-leyline", "always", "Tap the Leyline", 44),
      namedResult("action-healing-energy", "always", "Healing Energy", 44),
    ],
    byValue: {
      1: [
        namedResult("action-throw-em-a-bone", 1, "Throw ’Em a Bone", 44),
        namedResult("action-ice-blast", 1, "Ice Blast", 44),
        namedResult("action-hand-cannon", 1, "Hand Cannon", 44),
        namedResult("action-spirit-slap", 1, "Spirit Slap", 44),
      ],
      2: [
        namedResult("action-defensive-energy", 2, "Defensive Energy", 44),
        namedResult("action-drunken-dash", 2, "Drunken Dash", 44),
        namedResult("action-lightning-strike", 2, "Lightning Strike", 44),
        namedResult("action-zipp-zapp", 2, "Zipp Zapp", 44),
        namedResult("action-smashed-bottle", 2, "Smashed Bottle", 44),
      ],
      3: [
        namedResult("action-secret-passage", 3, "Secret Passage", 44),
        namedResult("action-false-claim", 3, "False Claim", 45),
        namedResult("action-bored-to-death", 3, "Bored to Death", 45),
        namedResult("action-shuriken", 3, "Shuriken", 45),
        namedResult("action-burn-stick", 3, "Burn Stick", 45),
      ],
      4: [
        namedResult("action-lifting-spirits", 4, "Lifting Spirits", 45),
        namedResult("action-retrofit", 4, "Retrofit", 45),
        namedResult("action-hellfire-shot", 4, "Hellfire Shot", 45),
        namedResult("action-alchemical-vial", 4, "Alchemical Vial", 45),
        namedResult("action-knock-heads", 4, "Knock Heads", 45),
      ],
      5: [
        namedResult("action-leap", 5, "Leap", 45),
        namedResult("action-obscene-feast", 5, "Obscene Feast", 45),
        namedResult("action-avalanche", 5, "Avalanche", 45),
        namedResult("action-compact-shotgun", 5, "Compact Shotgun", 45),
        namedResult("action-tangling-roots", 5, "Tangling Roots", 45),
      ],
      6: [
        namedResult("action-supportive-measures", 6, "Supportive Measures", 46),
        namedResult("action-revitalize", 6, "Revitalize", 46),
        namedResult("action-covert-agent", 6, "Covert Agent", 46),
        namedResult("action-bone-javelin", 6, "Bone Javelin", 46),
        namedResult("action-resupply", 6, "Resupply", 46),
      ],
      7: [
        namedResult("action-fade-into-memory", 7, "Fade Into Memory", 46),
        namedResult("action-steamroller", 7, "Steamroller", 46),
        namedResult("action-contract-kill", 7, "Contract Kill", 46),
        namedResult("action-flare-gun", 7, "Flare Gun", 46),
        namedResult("action-fishin-gear", 7, "Fishin’ Gear", 46),
      ],
      8: [
        namedResult("action-nitro-boost", 8, "Nitro Boost", 46),
        namedResult("action-falling-skies", 8, "Falling Skies", 46),
        namedResult("action-spilling-secrets", 8, "Spilling Secrets", 47),
        namedResult("action-giants-bane", 8, "Giant’s Bane", 47),
        namedResult("action-dynamite-punch", 8, "Dynamite Punch", 47),
      ],
      9: [
        namedResult("action-unstable-ground", 9, "Unstable Ground", 47),
        namedResult("action-50ft-of-silk-rope", 9, "50ft of Silk Rope", 47),
        namedResult("action-breath-of-fire", 9, "Breath of Fire", 47),
        namedResult("action-netgun", 9, "Netgun", 47),
        namedResult("action-balanced-sword", 9, "Balanced Sword", 47),
      ],
      10: [
        namedResult("action-a-cage-for-all", 10, "A Cage for All", 47),
        namedResult("action-cleansing-shield", 10, "Cleansing Shield", 47),
        namedResult("action-whip-vault", 10, "Whip Vault", 47),
        namedResult("action-mortar-strike", 10, "Mortar Strike", 47),
        namedResult("action-absolute-control", 10, "Absolute Control", 48),
        namedResult("action-outmaneuver", 10, "Outmaneuver", 48),
        namedResult("action-intuition", 10, "Intuition", 48),
        namedResult("action-frightening-reminder", 10, "Frightening Reminder", 48),
        namedResult("action-objection", 10, "“Objection!”", 48),
        namedResult("action-chesterfield-shotgun", 10, "Chesterfield Shotgun", 48),
        namedResult("action-up-we-go", 10, "“Up We Go!”", 48),
      ],
      11: [
        namedResult("action-turn-a-profit", 11, "Turn a Profit", 48),
        namedResult("action-raging-bellow", 11, "Raging Bellow", 48),
        namedResult("action-mirrored-malice", 11, "Mirrored Malice", 48),
        namedResult("action-ansatsu-rifle", 11, "Ansatsu Rifle", 48),
        {
          ...actionSnapshot({
            id: "action-runic-blade",
            name: "Runic Blade",
            type: "attack",
            range: "1\"",
            rangeType: "melee",
            skill: "6",
            resist: "Df",
            damage: "3",
            text: "This model heals 1.",
          }),
          value: 11,
          page: 48,
        },
      ],
      12: [
        namedResult("action-fallow-night", 12, "Fallow Night", 49),
        namedResult("action-blast-to-bits", 12, "Blast to Bits", 49),
        namedResult("action-sundering", 12, "Sundering", 49),
        namedResult("action-clockwork-seeker", 12, "Clockwork Seeker", 49),
        namedResult("action-mind-barbs", 12, "Mind Barbs", 49),
      ],
      13: [
        namedResult("action-obey", 13, "Obey", 49),
        namedResult("action-expanding-influence", 13, "Expanding Influence", 49),
        namedResult("action-onward", 13, "Onward", 49),
        namedResult("action-dark-bargain", 13, "Dark Bargain", 49),
        namedResult("action-broken-illusions", 13, "Broken Illusions", 49),
        namedResult("action-long-carbine", 13, "Long Carbine", 49),
      ],
    },
    naturalJoker: namedResult("action-natural-joker-choose", "natural-joker", "Choose", 49),
  };

  const TIER_2_ABILITIES = {
    always: [
      namedResult("ability-escape-path", "always", "Escape Path", 50),
      namedResult("ability-double-tap", "always", "Double Tap", 50),
      namedResult("ability-ethereal-protection", "always", "Ethereal Protection", 50),
    ],
    byValue: {
      1: [
        namedResult("ability-ruthless", 1, "Ruthless", 50),
        namedResult("ability-evasive", 1, "Evasive", 50),
      ],
      2: [
        namedResult("ability-nose-for-decay", 2, "Nose for Decay", 50),
        namedResult("ability-trample", 2, "Trample", 50),
      ],
      3: [
        namedResult("ability-amplify-power", 3, "Amplify Power", 50),
        namedResult("ability-ungentlemanly-affairs", 3, "Ungentlemanly Affairs", 50),
      ],
      4: [
        namedResult("ability-fun-prizes", 4, "Fun Prizes", 50),
        namedResult("ability-construct-savant", 4, "Construct Savant", 50),
      ],
      5: [
        namedResult("ability-shouting-orders", 5, "Shouting Orders", 50),
        namedResult("ability-nullify-magic", 5, "Nullify Magic", 50),
      ],
      6: [
        namedResult("ability-deadly-pursuit", 6, "Deadly Pursuit", 50),
        namedResult("ability-flight", 6, "Flight", 50),
      ],
      7: [
        namedResult("ability-scuttle", 7, "Scuttle", 50),
        namedResult("ability-nefarious-pact", 7, "Nefarious Pact", 51),
      ],
      8: [
        namedResult("ability-entourage", 8, "Entourage", 51),
        namedResult("ability-chatty", 8, "Chatty", 51),
      ],
      9: [
        namedResult("ability-escape-plan", 9, "Escape Plan", 51),
        namedResult("ability-taskmaster", 9, "Taskmaster", 51),
      ],
      10: [
        namedResult("ability-lead-the-patrol", 10, "Lead the Patrol", 51),
        namedResult("ability-serene-countenance", 10, "Serene Countenance", 51),
      ],
      11: [
        namedResult("ability-butterfly-jump", 11, "Butterfly Jump", 51),
        namedResult("ability-fortify-the-spirit", 11, "Fortify the Spirit", 51),
      ],
      12: [
        namedResult("ability-extended-reach", 12, "Extended Reach", 51),
        namedResult("ability-stealth", 12, "Stealth", 51),
      ],
      13: [
        namedResult("ability-warning-growl", 13, "Warning Growl", 51),
        namedResult("ability-disguised", 13, "Disguised", 51),
      ],
    },
    naturalJoker: namedResult("ability-natural-joker-choose", "natural-joker", "Choose", 51),
  };

  const SUMMONING_ADVANCEMENTS = [
    actionSnapshot({
      id: "summoning-formed-of-blood",
      name: "Formed of Blood",
      type: "tactical",
      range: "8\"",
      skill: "0",
      tn: "8",
      text:
        "Once per activation. Target an ally within 3\" of an enemy. Replace the target with a model of cost 5 or less that shares at least one keyword with this model.",
    }),
    actionSnapshot({
      id: "summoning-drawn-to-weakness",
      name: "Drawn to Weakness",
      type: "tactical",
      range: "8\"",
      skill: "0",
      tn: "8",
      text:
        "Once per activation. Enemy only. Remove a friendly token from the target. Summon a model of cost 5 or less that shares at least one keyword with this model with half its maximum health in base contact with the target.",
    }),
    actionSnapshot({
      id: "summoning-rally-point",
      name: "Rally Point",
      type: "tactical",
      range: "8\"",
      skill: "0",
      tn: "8",
      text:
        "Once per activation. Target a friendly marker within 3\" of an enemy. Summon a model of cost 5 or less that shares at least one keyword with this model with half its maximum health in base contact with the target, then remove the target.",
    }),
    actionSnapshot({
      id: "summoning-stolen-plans",
      name: "Stolen Plans",
      type: "tactical",
      range: "8\"",
      skill: "0",
      tn: "10",
      text:
        "Once per activation. Target an enemy marker. Summon a model of cost 5 or less that shares at least one keyword with this model with half its maximum health in base contact with the target, then remove the target.",
    }),
    actionSnapshot({
      id: "summoning-called-into-being",
      name: "Called into Being",
      type: "attack",
      range: "8\"",
      rangeType: "magic",
      skill: "6",
      resist: "Wp",
      damage: "2",
      text:
        "This action cannot target the same model more than once per activation. Summon a model of cost 3 or less that shares at least one keyword with this model within 2\" of the target.",
    }),
    actionSnapshot({
      id: "summoning-swarm-the-place",
      name: "Swarm the Place",
      type: "tactical",
      range: "8\"",
      skill: "0",
      tn: "4",
      text:
        "Enemy only. This action has a raise value of 3. This action may not target the same model more than once per activation. Summon a peon that shares at least one keyword with this model within 3\" of the target. For each raise this action receives, summon one additional peon within 3\" of the target.",
    }),
    actionSnapshot({
      id: "summoning-muster-point",
      name: "Muster Point",
      type: "tactical",
      range: "1\"",
      skill: "0",
      tn: "8",
      stoneCost: 1,
      text:
        "Once per activation. Target a piece of terrain that was not targeted by this action this game. Summon a model of cost 5 or less that shares at least one keyword with this model with half its maximum health within range and in base contact with the target.",
    }),
  ].map((entry) => ({ ...entry, page: 54 }));

  const TOTEM_PROFILES = [
    {
      id: "backwoods-bootlegger",
      flip: 1,
      name: "Backwoods Bootlegger",
      page: 52,
      stats: { df: 5, wp: 5, sp: 6, health: 9 },
      abilities: [],
      attacks: [
        actionSnapshot({
          id: "panic-response",
          name: "Panic Response",
          type: "attack",
          range: "1\"",
          rangeType: "melee",
          skill: "5",
          resist: "Df",
          damage: "1",
          text:
            "If this model has more cards in its control hand than the target, this action receives a +.",
        }),
      ],
      tacticals: [
        actionSnapshot({
          id: "satisfied-customer",
          name: "Satisfied Customer",
          type: "tactical",
          range: "12\"",
          skill: "0",
          tn: "7",
          signature: true,
          text:
            "Once per activation. Friendly only. Move the target up to 4\", then make a Scheme marker in base contact with the target.",
        }),
      ],
    },
    {
      id: "cursemonger",
      flip: 2,
      name: "Cursemonger",
      page: 52,
      stats: { df: 6, wp: 6, sp: 6, health: 9 },
      abilities: [
        {
          id: "beneficial-curses",
          name: "Beneficial Curses",
          text:
            "While this model has an enemy token, it receives a + to its Df and Wp duels.",
        },
      ],
      attacks: [
        actionSnapshot({
          id: "shared-curse",
          name: "Shared Curse",
          type: "attack",
          range: "1\"",
          rangeType: "melee",
          skill: "5",
          resist: "Df",
          damage: "2",
          signature: true,
          text:
            "Choose a token on this model. Target gains the chosen token, then this model may remove the chosen token from itself.",
        }),
      ],
      tacticals: [],
    },
    {
      id: "shadowrunner",
      flip: 3,
      name: "Shadowrunner",
      page: 52,
      stats: { df: 5, wp: 5, sp: 7, health: 9 },
      abilities: [],
      attacks: [
        actionSnapshot({
          id: "shove",
          name: "Shove",
          type: "attack",
          range: "1\"",
          rangeType: "melee",
          skill: "5",
          skillSuits: ["crow"],
          resist: "Df",
          text:
            "Move the target 2\". For each raise this action receives, move the target an additional +1\".",
        }),
      ],
      tacticals: [
        actionSnapshot({
          id: "leap",
          name: "Leap",
          type: "tactical",
          range: "6\"",
          skill: "0",
          tn: "8",
          signature: true,
          text: "Once per activation. Place this model anywhere within range.",
        }),
      ],
    },
    {
      id: "gearwright",
      flip: 4,
      name: "Gearwright",
      page: 52,
      stats: { df: 5, wp: 5, sp: 6, health: 9 },
      abilities: [
        {
          id: "construct-savant",
          name: "Construct Savant",
          text: "This model receives a + when it targets a construct model.",
        },
      ],
      attacks: [
        actionSnapshot({
          id: "heavy-wrench",
          name: "Heavy Wrench",
          type: "attack",
          range: "1\"",
          rangeType: "melee",
          skill: "5",
          resist: "Df",
          damage: "2",
          signature: true,
          triggers: [
            {
              id: "improvised-mechanics",
              name: "Improvised Mechanics",
              suit: "soulstone",
              stoneCost: 1,
              text: "Once per activation. Draw two cards, then discard a card.",
            },
          ],
        }),
      ],
      tacticals: [],
    },
    {
      id: "demolitionist",
      flip: 5,
      name: "Demolitionist",
      page: 52,
      stats: { df: 5, wp: 5, sp: 6, health: 9 },
      abilities: [],
      attacks: [
        actionSnapshot({
          id: "combat-knife",
          name: "Combat Knife",
          type: "attack",
          range: "1\"",
          rangeType: "melee",
          skill: "5",
          resist: "Df",
          damage: "2",
        }),
      ],
      tacticals: [
        actionSnapshot({
          id: "blow-charge",
          name: "Blow Charge",
          type: "tactical",
          range: "8\"",
          skill: "0",
          tn: "6",
          signature: true,
          text:
            "Once per activation. Target a marker. Enemy models within 2\" of the target must pass a TN 12 Sp duel or be dealt 2 damage. Remove the target after resolving triggers.",
        }),
      ],
    },
    {
      id: "logistics-officer",
      flip: 6,
      name: "Logistics Officer",
      page: 52,
      stats: { df: 5, wp: 5, sp: 6, health: 9 },
      abilities: [],
      attacks: [
        actionSnapshot({
          id: "sword",
          name: "Sword",
          type: "attack",
          range: "1\"",
          rangeType: "melee",
          skill: "5",
          positiveSkill: true,
          resist: "Df",
          damage: "2",
        }),
      ],
      tacticals: [
        actionSnapshot({
          id: "expanding-influence",
          name: "Expanding Influence",
          type: "tactical",
          range: "6\"",
          skill: "0",
          tn: "4",
          signature: true,
          text:
            "Ally or friendly minion only. Move the target up to 4\" toward a friendly model in its LoS.",
        }),
      ],
    },
    {
      id: "chance-taker",
      flip: 7,
      name: "Chance Taker",
      page: 52,
      stats: { df: 6, wp: 5, sp: 6, health: 9 },
      abilities: [
        {
          id: "lucky-draw",
          name: "Lucky Draw",
          text:
            "Once per activation. If this model has no cards in its control hand, it may receive a + to a duel.",
        },
      ],
      attacks: [
        actionSnapshot({
          id: "lucky-guess",
          name: "Lucky Guess",
          type: "attack",
          range: "1\"",
          rangeType: "melee",
          skill: "6",
          resist: "Df",
          damage: "1",
          text:
            "This model may look at the top card of any fate deck and may choose to discard it.",
        }),
      ],
      tacticals: [
        actionSnapshot({
          id: "trust-to-luck",
          name: "Trust to Luck",
          type: "tactical",
          range: "6\"",
          signature: true,
          text:
            "Once per activation. Flip a card which may not be cheated. If it is a Mask or Ram, make a Scheme marker within 3\". If it is a Crow or Tome, this model is dealt 2 damage and draws a card.",
        }),
      ],
    },
    {
      id: "night-marketeer",
      flip: 8,
      name: "Night Marketeer",
      page: 52,
      stats: { df: 5, wp: 5, sp: 6, health: 9 },
      abilities: [],
      attacks: [
        actionSnapshot({
          id: "lucky-break",
          name: "Lucky Break",
          type: "attack",
          range: "1\"",
          rangeType: "melee",
          skill: "5",
          resist: "Df",
          damage: "1",
          text:
            "If the target has already activated this turn, this action receives a +.",
        }),
      ],
      tacticals: [
        actionSnapshot({
          id: "jury-rig",
          name: "Jury Rig",
          type: "tactical",
          signature: true,
          text:
            "Discard a card. Draw a non-joker card in this model’s discard pile with a value equal to or less than the value of the discarded card +1.",
        }),
      ],
    },
    {
      id: "gravehand",
      flip: 9,
      name: "Gravehand",
      page: 53,
      stats: { df: 5, wp: 5, sp: 6, health: 9 },
      abilities: [],
      attacks: [
        actionSnapshot({
          id: "graves-curse",
          name: "Grave’s Curse",
          type: "attack",
          range: "1\"",
          rangeType: "melee",
          skill: "5",
          resist: "Df",
          damage: "1",
          text: "If this action receives a raise, the target gains an Injured token.",
        }),
      ],
      tacticals: [
        actionSnapshot({
          id: "command-corpse",
          name: "Command Corpse",
          type: "tactical",
          range: "8\"",
          skill: "0",
          tn: "6",
          signature: true,
          text:
            "Target a Remains marker. Select an action printed on an ally within 3\" of the target. This model declares the selected action, drawing range and LoS from the target. Then, remove the target.",
        }),
      ],
    },
    {
      id: "willing-vessel",
      flip: 10,
      name: "Willing Vessel",
      page: 53,
      stats: { df: 4, wp: 5, sp: 6, health: 10 },
      abilities: [
        {
          id: "tempting-fate",
          name: "Tempting Fate",
          text:
            "Once per game. When a friendly master is killed, this model may drain two Soulstones. If it does so, deal 4 irreducible damage to this model, then the friendly master heals 4.",
        },
      ],
      attacks: [
        actionSnapshot({
          id: "bloodsuck",
          name: "Bloodsuck",
          type: "attack",
          range: "1\"",
          rangeType: "melee",
          skill: "5",
          resist: "Df",
          damage: "1",
          text: "This model heals 1.",
        }),
      ],
      tacticals: [
        actionSnapshot({
          id: "insatiable-maw",
          name: "Insatiable Maw",
          type: "tactical",
          range: "1\"",
          skill: "0",
          tn: "6",
          signature: true,
          text:
            "Once per activation. Target a Scheme marker. Remove the target and heal 2.",
        }),
      ],
    },
    {
      id: "ringmaster",
      flip: 11,
      name: "Ringmaster",
      page: 53,
      stats: { df: 5, wp: 6, sp: 6, health: 9 },
      abilities: [],
      attacks: [
        actionSnapshot({
          id: "dismissive-wave",
          name: "Dismissive Wave",
          type: "attack",
          range: "1\"",
          rangeType: "melee",
          skill: "5",
          resist: "Wp",
          damage: "1",
        }),
        actionSnapshot({
          id: "lure",
          name: "Lure",
          type: "attack",
          range: "12\"",
          rangeType: "magic",
          skill: "6",
          resist: "Wp",
          tn: "12",
          signature: true,
          text:
            "This action may target friendly models. Move the target its Sp toward this model.",
        }),
      ],
      tacticals: [],
    },
    {
      id: "mad-surgeon",
      flip: 12,
      name: "Mad Surgeon",
      page: 53,
      stats: { df: 5, wp: 4, sp: 6, health: 9 },
      abilities: [],
      attacks: [
        actionSnapshot({
          id: "dirty-knife",
          name: "Dirty Knife",
          type: "attack",
          range: "1\"",
          rangeType: "melee",
          skill: "5",
          resist: "Df",
          damage: "1",
          text: "Target gains a Poison token.",
        }),
      ],
      tacticals: [
        actionSnapshot({
          id: "healing-energy",
          name: "Healing Energy",
          type: "tactical",
          range: "8\"",
          skill: "0",
          tn: "4",
          signature: true,
          stoneCost: 1,
          text:
            "Target heals 2. For each raise this action receives, the target heals an additional +2.",
        }),
      ],
    },
    {
      id: "raging-colossus",
      flip: 13,
      name: "Raging Colossus",
      page: 53,
      stats: { df: 5, wp: 5, sp: 6, health: 9 },
      abilities: [],
      attacks: [
        actionSnapshot({
          id: "huge-fist",
          name: "Huge Fist",
          type: "attack",
          range: "2\"",
          rangeType: "melee",
          skill: "5",
          resist: "Df",
          damage: "3",
        }),
      ],
      tacticals: [
        actionSnapshot({
          id: "tenacity",
          name: "Tenacity",
          type: "tactical",
          signature: true,
          text: "Discard a card. This model heals 2.",
        }),
      ],
    },
    {
      id: "sniveling-coward",
      flip: "black-joker",
      name: "Sniveling Coward",
      page: 53,
      stats: { df: 4, wp: 4, sp: 6, health: 6 },
      abilities: [
        {
          id: "fight-another-day",
          name: "Fight Another Day",
          text:
            "If this model is in play at the end of a game during which it damaged an enemy model, it may be permanently replaced with any non-joker totem on the list. It retains any advances it gained.",
        },
      ],
      attacks: [
        actionSnapshot({
          id: "false-bravado",
          name: "False Bravado",
          type: "attack",
          range: "6\"",
          rangeType: "magic",
          skill: "5",
          resist: "Df",
          damage: "1",
          text:
            "If this attack received a raise, this model may move up to 4\" away from the target.",
        }),
      ],
      tacticals: [],
    },
    {
      id: "mini-master",
      flip: "red-joker",
      name: "Mini-Master",
      page: 53,
      stats: { df: 5, wp: 5, sp: 6, health: 9 },
      abilities: [],
      attacks: [],
      tacticals: [],
      specialActionChoice:
        "Choose one action on a master that shares a keyword with your leader. The action may not list a model by name or cause the totem to be replaced with another model. This model gains that action without any triggers.",
    },
  ];

  window.MalifauxAdvancementData = Object.freeze({
    version: 2,
    schema: deepFreeze({
      xpPositions: 39,
      tierRange: [1, 4],
      snapshotPolicy: "immutable-record-with-catalog-fallback",
      flipValues: [
        ...Array.from({ length: 13 }, (_, index) => String(index + 1)),
        "black-joker",
        "red-joker",
      ],
    }),
    xpTrack: deepFreeze(XP_TRACK),
    xpThresholds: deepFreeze(XP_THRESHOLDS),
    tables: deepFreeze(TABLES),
    tier1: deepFreeze({
      attackModification: ATTACK_MODIFICATION_OPTIONS,
      tacticalModification: TACTICAL_MODIFICATION_OPTIONS,
    }),
    tier2: deepFreeze({
      actions: TIER_2_ACTIONS,
      abilities: TIER_2_ABILITIES,
    }),
    tier3: deepFreeze({
      summoning: SUMMONING_ADVANCEMENTS,
      totems: TOTEM_PROFILES,
    }),
  });
})();
